name: Bump Version

on:
  push:
    branches:
      - main

permissions:
  contents: write
      
jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
      - run: go version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Git
        run: sudo apt-get install git

      - name: Install GoReleaser
        run: echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list && sudo apt update && sudo apt install goreleaser
        
      - name: Configure Git
        run: |
          git config --global user.name "lovelyoyrmia"
          git config --global user.email "mokalulovelyo@gmail.com"

      - name: Bump version
        run: python bump_version.py patch
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      
      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}